### ISSUE TITLE
Permission request: add your userscript to my list

### ISSUE THREAD

**Issue by lufte** [cryzed/qutebrowser-userscripts#1]
Hi, I'm putting together a list of qutebrowser userscripts here https://github.com/lufte/awesome-qutebrowser-userscripts.git. I'm asking developers of userscripts here on Github to either send me a pull request with the addition of their repo or to simply give me permission to link it myself. 

Let me know if you're interested. Thanks.

**Comment by cryzed** [comment]
Hey, that's totally fine. Although the `qute-pass` script in this repository is outdated, the newest can be one found [directly](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-pass) in the official qutebrowser repository. I'll remove the old version from this repository. Feel free to mention `qute-pass` and link to this repository, sure!

**Comment by lufte** [comment]
Thanks, I also noticed that some other userscripts are being included in qutebrowser by default and they are also putting together a list of third-party userscripts right in the browser itself, so my list doesn't really make sense now. Thanks for your time!
