### ISSUE TITLE
In qute-pass does -d option is used in 'secret' mode ?

### ISSUE THREAD

**Issue by chomwitt** [cryzed/qutebrowser-userscripts#2]
As i understand if a  username is in path then a dmenu will allow you to select
among usernames for one domain.
But in '-U secret' where username in written in the pass file is it of any use?
Can we have 2 usernames in a pass-store file?

**Comment by cryzed** [comment]
Hey, you'd better ask this question here: https://github.com/qutebrowser/qutebrowser -- I haven't maintained this script in a while, and it has since changed significantly.

**Comment by chomwitt** [comment]
ok . thanks.
